version: '3.4'

services:
  postgres:
    container_name: mysql
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=BaqV7knGfeuYzC
      - MYSQL_DATABASE=api
    volumes:
      - ./db:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

  phpAdmin:
    container_name: phpmyadmin
    image: phpmyadmin
    environment:
      PMA_HOST: mysql
    ports:
      - "8080:80"

  se_sta_api:
    container_name: api
    image: ${DOCKER_REGISTRY-}sestaapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://[::]:443;http://[::]:80
    build:
      context: ./SE_StA_API
      dockerfile: Dockerfile
    ports:
      - "50000:80"
      - "50001:443"
    depends_on:
      - postgres
  
  angular:
    container_name: angular
    image: ${DOCKER_REGISTRY-}sestaangular
    build: ./SE_StA_Angular
    ports:
      - "4200:80"
    depends_on:
      - se_sta_api
  